import { isDockerAvailable, runInDockerSandbox } from '../sandbox/dockerSandbox';

export interface LlmExecutionResult {
  text: string;
  structuredData: Record<string, unknown>;
  diffProposals?: Array<{
    filePath: string;
    originalContent: string;
    proposedContent: string;
    diffSummary: string;
  }>;
}

export async function executeLlmTask(
  skill: string,
  input: Record<string, unknown>,
  isMock: boolean,
  provider: string,
  apiKey: string
): Promise<LlmExecutionResult> {
  const instruction = (input.instruction as string) || (input.prompt as string) || 'Coding task execution';
  const targetFile = (input.targetFile as string) || 'src/index.ts';
  const projectPath = (input.projectPath as string) || 'local-project';

  if (skill === 'code-generation') {
    const proposedContent = `// Code generated by A2A Desktop Coding Agent\n// Instruction: ${instruction}\n\nexport function executeTask() {\n  console.log("Task executed successfully in ${projectPath}");\n  return { success: true, timestamp: new Date().toISOString() };\n}\n`;

    return {
      text: `Generated code refactoring for ${targetFile} based on instruction: "${instruction}"`,
      structuredData: {
        skill: 'code-generation',
        projectPath,
        targetFile,
        instruction,
        status: 'diff_proposed',
      },
      diffProposals: [
        {
          filePath: targetFile,
          originalContent: '// Existing file content\n',
          proposedContent,
          diffSummary: `+ Inserted executeTask() implementation for ${targetFile}`,
        },
      ],
    };
  }

  if (skill === 'code-runner') {
    const dockerReady = await isDockerAvailable();
    const forceDockerCheck = input.requireDockerCheck === true || process.env.REQUIRE_DOCKER_TEST === 'true';

    // Per SANDBOX.md: If Docker isn't running, block ONLY the Debug/Test agent (code-runner)
    if (!dockerReady && (!isMock || forceDockerCheck)) {
      return {
        text: `[Sandbox Error] Docker is not installed or running. Code execution (Debug/Test agent) requires Docker. Please start Docker and try again.`,
        structuredData: {
          skill: 'code-runner',
          error: 'docker_unavailable',
          status: 'blocked',
          message:
            'Docker is not installed or running. Code execution (Debug/Test agent) requires Docker. Please start Docker and try again.',
        },
      };
    }

    if (isMock && !dockerReady && !forceDockerCheck) {
      return {
        text: `Sandboxed execution complete for ${targetFile}.\nStandard Output:\n> Running test suite...\n> 5/5 tests passed in 42ms. Clean exit (0).`,
        structuredData: {
          skill: 'code-runner',
          exitCode: 0,
          stdout: 'Running test suite...\n5/5 tests passed in 42ms.',
          stderr: '',
          sandbox: {
            dockerAvailable: false,
            mock: true,
            limits: { cpus: 2, memory: '2g', timeoutSeconds: 60, network: 'none' },
          },
        },
      };
    }

    // Execute within short-lived Docker container with resource limits & volume isolation
    const sandboxResult = await runInDockerSandbox({
      projectPath: (input.projectPath as string) || process.cwd(),
      command: (input.command as string) || (input.testCommand as string) || 'npm test',
      timeoutSeconds: (input.timeoutSeconds as number) || 60,
      cpus: (input.cpus as number) || 2,
      memory: (input.memory as string) || '2g',
      allowNetwork: (input.allowNetwork as boolean) || false,
    });

    if (!sandboxResult.dockerAvailable) {
      return {
        text: `[Sandbox Error] ${sandboxResult.error}`,
        structuredData: {
          skill: 'code-runner',
          error: 'docker_unavailable',
          status: 'blocked',
          message: sandboxResult.error,
        },
      };
    }

    return {
      text: sandboxResult.success
        ? `Sandboxed execution complete for ${targetFile}.\nExit Code: ${sandboxResult.exitCode}\nDuration: ${sandboxResult.durationMs}ms\nStandard Output:\n${sandboxResult.stdout}`
        : `Sandboxed execution failed for ${targetFile}.\nExit Code: ${sandboxResult.exitCode}\nDuration: ${sandboxResult.durationMs}ms\nError:\n${sandboxResult.stderr || sandboxResult.error}`,
      structuredData: {
        skill: 'code-runner',
        exitCode: sandboxResult.exitCode,
        stdout: sandboxResult.stdout,
        stderr: sandboxResult.stderr,
        durationMs: sandboxResult.durationMs,
        sandbox: {
          dockerAvailable: true,
          limits: { cpus: 2, memory: '2g', timeoutSeconds: 60, network: 'none' },
        },
      },
    };
  }

  if (skill === 'git-operations') {
    return {
      text: `Git Operation '${instruction}' executed on ${projectPath}.\nOn branch main\nYour branch is up to date with 'origin/main'.\n\nChanges ready for commit.`,
      structuredData: {
        skill: 'git-operations',
        branch: 'main',
        status: 'clean',
        output: 'On branch main. Nothing to commit, working tree clean.',
      },
    };
  }

  if (skill === 'code-review') {
    return {
      text: `Code Review Summary for ${projectPath}:\n1. Architecture: Excellent microservice decoupling.\n2. Security: Prompt injection sanitizer verified.\n3. Performance: Parallel execution overhead optimal. No critical vulnerabilities found.`,
      structuredData: {
        skill: 'code-review',
        score: 'A+',
        suggestions: ['Add optional inline telemetry logger', 'Optimize static asset bundle size'],
      },
    };
  }

  if (skill === 'file-operations') {
    return {
      text: `File operation completed for ${targetFile} in project ${projectPath}.`,
      structuredData: {
        skill: 'file-operations',
        targetFile,
        action: 'processed',
      },
    };
  }

  // Default fallback execution response
  console.log(`[LLM] Executing task with provider '${provider}' and skill '${skill}'`);
  return {
    text: `Execution output from AI Provider '${provider}' for skill '${skill}' (${instruction})`,
    structuredData: {
      provider,
      status: 'executed',
      input,
      hasKey: Boolean(apiKey),
    },
  };
}
